#!/usr/bin/env sh

set -eu

root=$(dirname $0)
. $root/common

usage() {
  cat <<EOF
Standard commands
root-ca           generate root CA
signing-ca        generate signing CA from root CA
version           pki tool version
EOF
}

version() {
  echo "pki 1.0.0.alpha  18 Mar 2020"
}

# default display help
command="help"

if [ $# -ge 1 ]; then
    command="$1"
fi

case "$command" in
  "root-ca")
    shift
    $root/create-root-ca $@ ;;
  "signing-ca")
    shift
    $root/create-signing-ca $@ ;;
  "version")
    version
    exit 0 ;;
  "help")
    usage
    exit 0 ;;
  *)
    fatal "invalid command '$1'; type help for a list" ;;
esac
